name: Spring CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar

      - name: Run tests
        run: mvn test

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Set recipient email based on github.actor
        id: set-email
        run: |
          email_recipient=""
          if [[ "${{ github.actor }}" == "FAYCAL-EL" ]]; then
            email_recipient="faysalelourrat@gmail.com"
          elif [[ "${{ github.actor }}" == "AbdessamadBounasseh" ]]; then
            email_recipient="abdessamad.bounasseh@uit.ac.ma"
          elif [[ "${{ github.actor }}" == "mery-eh" ]]; then
            email_recipient="meryem.elhassouni1@uit.ac.ma"
          elif [[ "${{ github.actor }}" == "moamine1996" ]]; then
            email_recipient="mohamedamine.elkaaba@uit.ac.ma"
          elif [[ "${{ github.actor }}" == "NashOmega" ]]; then
            email_recipient="bernardalphaomegadekpe@gmail.com"
          fi
          echo "::set-output name=email_recipient::$email_recipient"
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build ${{ needs.build.outputs.job1_status }} for ${{ github.workflow }} on ${{ github.ref }}"
          body: |
            Build ${{ needs.build.outputs.job1_status }} for ${{ github.workflow }} on ${{ github.ref }}.
            See the build log here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ steps.set-email.outputs.email_recipient }}
          from: "${{ secrets.EMAIL_SENDER }}"
